### ISSUE TITLE
Call to undefined method Guzzle\Http\Client::request()

### ISSUE THREAD

**Issue by multras** [thomasbnielsen/omnipay-quickpay#16]
I'm using `Aimeos` extension with TYPO3 v9.5.14 to create a Shop website.

I have a problem with the return urls from the payment gateway to the website : `continueurl` / `cancelurl` / `callbackurl` . I get the following error 

    Call to undefined method Guzzle\Http\Client::request()
    in /var/www/example.com/typo3conf/ext/aimeos_pay/Resources/Libraries/nobrainerweb/omnipay-quickpay/src/Message/CompleteRequest.php line 44

This is the code :  

    public function sendData($data)
    {
        $httpResponse =  $this->httpClient->request('get', $this->getEndPoint() . '/payments/' . $this->getTransactionReference(),
            [
                'Authorization' => 'Basic ' . base64_encode(":" . $this->getApikey()),
                'Accept-Version' => 'v10',
                'Content-Type' => 'application/json'
            ]
        );
        return $this->response = new Response($this, $httpResponse->getBody()->getContents());
    }

Guzzle is properly installed through Composer.

    composer require guzzlehttp/guzzle

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/KN9pE.png

**Comment by i34a23** [comment]
any solution ?
